export { default as Centros } from "./Centros";
export { default as Citas } from "./Citas";
export { default as ErrorPage } from "./Error";
export { default as Farmacia } from "./Farmacia";
export { default as Landing } from "./Landing";
export { default as Login } from "./Login.tsx";
export { default as Home } from "./Home.tsx";
export { default as CitaDetail } from "./CitaDetail.tsx";
export { default as About } from "./About.tsx";
