export { default as Centros } from "./Centros";
export { default as Citas } from "./Citas";
export { default as Config } from "./Config";
export { default as Datos } from "./Datos";
export { default as Error } from "./Error";
export { default as Farmacia } from "./Farmacia";
export { default as Informacion } from "./Informacion";
export { default as Landing } from "./Landing";
export { default as Users } from "./Users";
